# Generated by Django 6.0.7 on 2026-07-30 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='cupo_maximo',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='codigo_qr',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='usuario',
        ),
        migrations.AddField(
            model_name='evento',
            name='link_pago',
            field=models.URLField(blank=True, help_text='Link de pago de Chrystal Records', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email_comprador',
            field=models.EmailField(default=140, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='nombre_comprador',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
    ]
