# Generated by Django 6.0.7 on 2026-07-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_evento_cupo_maximo_remove_ticket_codigo_qr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='link_pago',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='flyers/'),
        ),
    ]
