# Generated by Django 6.0.7 on 2026-07-31 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_evento_link_pago_evento_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comprador', models.CharField(max_length=150)),
                ('email_comprador', models.EmailField(max_length=254)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=250, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='eventos.evento')),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
