# Generated by Django 6.0.7 on 2026-08-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_orden_delete_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='email_comprador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orden',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='mercadopago_preference_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre_comprador',
            field=models.CharField(max_length=100),
        ),
    ]
