# Generated by Django 6.0.7 on 2026-08-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
