# Generated by Django 6.0.7 on 2026-09-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_orden_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='link_video',
            field=models.URLField(blank=True, help_text='Link embed de YouTube o Vimeo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_contenido',
            field=models.CharField(choices=[('stream', 'Stream en Vivo'), ('pelicula', 'Película')], default='pelicula', max_length=10),
        ),
    ]
