# Generated by Django 6.0.7 on 2026-09-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_evento_link_video_evento_tipo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='modo_acceso',
            field=models.CharField(choices=[('ON_DEMAND', 'On Demand (Disponible siempre)'), ('FUNCION', 'Función Programada (Fecha y hora fija)')], default='ON_DEMAND', max_length=20),
        ),
    ]
