# Generated by Django 6.0.7 on 2026-09-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='modo_acceso',
        ),
    ]
