# Generated by Django 6.0.7 on 2026-09-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_remove_evento_modo_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='modo_acceso',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial (con QR en puerta)'), ('ON_DEMAND', 'On Demand (Disponible siempre)'), ('FUNCION', 'Función Programada (Fecha y hora fija)')], default='PRESENCIAL', max_length=20),
        ),
    ]
