# Generated by Django 6.0.7 on 2026-09-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_evento_modo_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_contenido',
            field=models.CharField(choices=[('stream', 'Stream en Vivo'), ('pelicula', 'Película'), ('show', 'Show / Concierto en Vivo')], default='pelicula', max_length=10),
        ),
    ]
