# Generated by Django 6.0.7 on 2026-09-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_alter_evento_tipo_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Banner')),
                ('imagen', models.ImageField(upload_to='banners/', verbose_name='Imagen del Banner')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Enlace (opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en la página?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
        ),
    ]
