# Generated by Django 6.0.7 on 2026-09-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_bannerpromocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='country_market',
            field=models.CharField(choices=[('ARS', 'Argentina (ARS) - 🇦🇷'), ('EUR', 'España (EUR) - 🇪🇸'), ('EUR', 'Francia (EUR) - 🇫🇷'), ('EUR', 'Italia (EUR) - 🇮🇹'), ('USD', 'Estados Unidos / Ecuador / Panamá (USD) - 🇺🇸/🇪🇨/🇵🇦'), ('CAD', 'Canadá (CAD) - 🇨🇦'), ('MXN', 'México (MXN) - 🇲🇽'), ('PYG', 'Paraguay (PYG) - 🇵🇾'), ('CLP', 'Chile (CLP) - 🇨🇱'), ('UYU', 'Uruguay (UYU) - 🇺🇾'), ('BRL', 'Brasil (BRL) - 🇧🇷'), ('AWG', 'Aruba (AWG) - 🇦🇼'), ('DOP', 'República Dominicana (DOP) - 🇩🇴'), ('TTD', 'Trinidad y Tobago (TTD) - 🇹🇹'), ('BZD', 'Dólar beliceño (BZD) - 🇧🇿'), ('GYD', 'Dólar guyanés (GYD) - 🇬🇾'), ('SRD', 'Dólar surinamés (SRD) - 🇸🇷')], default='ARS', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='currency_target',
            field=models.CharField(default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='evento',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='price_in_ars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
